Repository veteransaffairscanada/vac-benefits-directory, pull requests merged in 2018-04, with the labels that each got.

#97 Use redux
  __tests__/A1_test.js
  __tests__/A2_test.js
  package.json
  pages/A1.js
  pages/A2.js
  pages/benefit_list.js
  store.js
  yarn.lock
Labels: complexity: 3

#98 Added a modal that will show up in the noscript tag with a hard link …
  __tests__/noscript_test.js
  components/layout.js
  components/noscript.js
  locales/en/common.json
  locales/fr/common.json
Labels: complexity: 2

#100 Footer fix #95
  components/footer.js
  components/layout.js
Labels: complexity: 1

#106 Use Airtable
  __tests__/components/benefit_card_test.js
  __tests__/components/selected_options_card_test.js
  __tests__/pages/A1_test.js
  __tests__/pages/A2_test.js
  __tests__/pages/A3_test.js
  components/benefit_cards.js
  components/selected_options_card.js
  package-lock.json
  package.json
  pages/A1.js
  pages/A2.js
  pages/A3.js
  store.js
  utils/airtable.js
  yarn.lock
Labels: complexity: 5

#111 fix some translation related issues
  __tests__/pages/A3_test.js
  components/select_button.js
  locales/en/common.json
  locales/fr/common.json
  pages/A1.js
  pages/A2.js
  pages/A3.js
Labels: bug

#125 Fix BenefitCard
  __tests__/components/benefit_card_test.js
  __tests__/pages/all-benefits_test.js
  components/benefit_cards.js
  components/footer.js
  pages/all-benefits.js
Labels: complexity: 2

#128 fix onClick error
  components/select_button.js
Labels: complexity: 1
